In [1]:
# importing dependencies

import pandas as pd
import os
import re
import calendar

In [2]:
# grabbing all the files in the "Resources_HR" directory

excel_files = [file for file in os.listdir("Resources_HR") if not file.startswith("~") and file.lower().endswith(".xls")]

In [3]:
# checking to see that all files were imported

print(len(excel_files))

22

In [10]:


concat=False;
for file in excel_files:
    year_month = re.sub("[^\d]", "", file)
    year = "20"+year_month[0:2]
    month = int(year_month[2:4])
    
    
    if(year in ["2012", "2013", "2014"]):
        sheet_name = "Table 10"
    elif(year in ['2015', '2016', '2017', '2018', '2019', '2020', '2021']):
        sheet_name = "TablesC5-C10 FiguresC1-C12"
    else:
        sheet_name = "TablesC5-C12 Figures C1-C20"
        
    
    survival_df = pd.read_excel(io='Resources_HR/'+file, sheet_name=sheet_name)
#     deceased_nation_df = pd.read_excel(io="Resources_LU/"+file, sheet_name=sheet_name+" - Deceased Nation")
#     living_df = pd.read_excel(io="Resources_LU/"+file, sheet_name=sheet_name+" - Living")
#     living_nation_df = pd.read_excel(io="Resources_LU/"+file, sheet_name=sheet_name+" - Living Nation")
        
    if(len(survival_df.index)>0):
        survival_df = survival_df.drop(survival_df.index[0])
#     if(len(deceased_nation_df.index)>0):
#         deceased_nation_df = deceased_nation_df.drop(deceased_nation_df.index[0])
#     if(len(living_df.index)>0):
#         living_df = living_df.drop(living_df.index[0])
#     if(len(living_nation_df.index)>0):
#         living_nation_df = living_nation_df.drop(living_nation_df.index[0])
        
    survival_df_cleaned = pd.DataFrame()
#     living_df_cleaned = pd.DataFrame()
    
    
    columns_to_keep = ["Unnamed: 0", ' ctr_cd', 'ctr_ty', 'ENTIRE_NAME', 'CTR_CD', 'CTR_TY', 'RELEASE_DATE', 'ORG', 
                   'GSR_AD_OBS_C1M', 'GSR_AD_OBS_C1Y', 'GSR_AD_OBS_C3Y', 
                   'GSR_AD_N_C1M', 'GSR_AD_N_C1Y', 'GSR_AD_N_C3Y', 
                   'GSR_P0_OBS_C1M', 'GSR_P0_OBS_C1Y', 'GSR_P0_OBS_C3Y', 
                   'GSR_P0_N_C1M', 'GSR_P0_N_C1Y', 'GSR_P0_C3Y']
    
    for column in columns_to_keep:
        if column in survival_df:
            survival_df_cleaned[column]=survival_df[column]
        elif column+" " in survival_df:
            survival_df_cleaned[column]=survival_df[column+" "]
        elif " "+column in survival_df:
            survival_df_cleaned[column]=survival_df[" "+column]
        elif " "+column+" " in survival_df:
            survival_df_cleaned[column]=survival_df[" "+column+" "]
            
#         if column in living_df:
#             living_df_cleaned[column]=living_df[column]
#         elif column+" " in living_df:
#             living_df_cleaned[column]=living_df[column+" "]
#         elif " "+column in living_df:
#             living_df_cleaned[column]=living_df[" "+column]
#         elif " "+column+" " in living_df:
#             living_df_cleaned[column]=living_df[" "+column+" "]

#     deceased_df_cleaned["D_OR_L"] = "D"
#     deceased_nation_df["D_OR_L"] = "D"
#     living_df_cleaned["D_OR_L"] = "L"
#     living_nation_df["D_OR_L"] = "L"
    
#     center_df = pd.concat([deceased_df_cleaned, living_df_cleaned], axis=0)
#     nation_df = pd.concat([deceased_nation_df, living_nation_df], axis=0)
    
    survival_df_cleaned["YEAR"]=year
    survival_df_cleaned["MONTH"]=month
#     nation_df["YEAR"]=year
#     nation_df["MONTH"]=month
    
    if(concat==True):
        merged_survival_df= pd.concat([merged_survival_df, survival_df_cleaned], axis=0)
#         merged_nation_df= pd.concat([merged_nation_df, nation_df], axis=0)
    else:
        merged_survival_df=survival_df_cleaned
#         merged_nation_df=nation_df
        concat=True

In [11]:
merged_survival_df

,Unnamed: 0,ctr_cd,ctr_ty,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_N_C1M,GSR_AD_N_C1Y,...,GSR_P0_OBS_C1M,GSR_P0_OBS_C1Y,GSR_P0_OBS_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH,ENTIRE_NAME,CTR_CD,CTR_TY
1,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Heart,0,2,12,41,41,...,0,0,0,13,13,2012,7,NaN,NaN,NaN
2,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Heart,0,2,10,21,21,...,,,,,,2012,7,NaN,NaN,NaN
3,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Heart,0,0,,3,3,...,0,9,12,51,51,2012,7,NaN,NaN,NaN
4,UAMS Medical Center (ARUA),ARUA,TX1,2012/07/13,Heart,,,0,,,...,,,,,,2012,7,NaN,NaN,NaN
5,Mayo Clinic Hospital (AZMC),AZMC,TX1,2012/07/13,Heart,1,2,8,41,41,...,,,,,,2012,7,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,University of Washington Medical Center (WAUW),WAUW,TX1,2014/06/17,Heart,7,7,5,49,49,...,,,0,,,2014,6,NaN,NaN,NaN
132,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Heart,0,1,3,8,8,...,0,6,4,36,36,2014,6,NaN,NaN,NaN
133,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Heart,0,0,0,4,4,...,,,,,,2014,6,NaN,NaN,NaN
134,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Heart,0,5,15,92,92,...,,,,,,2014,6,NaN,NaN,NaN
135,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Heart,0,2,5,40,40,...,,,,,,2014,6,NaN,NaN,NaN

In [23]:
column_adding = merged_survival_df.copy()

column_adding = column_adding.fillna('')

column_adding['ENTIRE_NAME'] = column_adding['ENTIRE_NAME'] + column_adding['Unnamed: 0']

column_adding

,Unnamed: 0,ctr_cd,ctr_ty,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_N_C1M,GSR_AD_N_C1Y,...,GSR_P0_OBS_C1M,GSR_P0_OBS_C1Y,GSR_P0_OBS_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH,ENTIRE_NAME,CTR_CD,CTR_TY
1,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Heart,0,2,12,41,41,...,0,0,0,13,13,2012,7,University of Alabama Hospital (ALUA),,
2,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Heart,0,2,10,21,21,...,,,,,,2012,7,Baptist Medical Center (ARBH),,
3,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Heart,0,0,,3,3,...,0,9,12,51,51,2012,7,Arkansas Children's Hospital (ARCH),,
4,UAMS Medical Center (ARUA),ARUA,TX1,2012/07/13,Heart,,,0,,,...,,,,,,2012,7,UAMS Medical Center (ARUA),,
5,Mayo Clinic Hospital (AZMC),AZMC,TX1,2012/07/13,Heart,1,2,8,41,41,...,,,,,,2012,7,Mayo Clinic Hospital (AZMC),,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,University of Washington Medical Center (WAUW),WAUW,TX1,2014/06/17,Heart,7,7,5,49,49,...,,,0,,,2014,6,University of Washington Medical Center (WAUW),,
132,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Heart,0,1,3,8,8,...,0,6,4,36,36,2014,6,Children's Hospital of Wisconsin (WICH),,
133,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Heart,0,0,0,4,4,...,,,,,,2014,6,Froedtert Memorial Lutheran Hospital (WISE),,
134,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Heart,0,5,15,92,92,...,,,,,,2014,6,Aurora St. Luke's Medical Center (WISL),,
135,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Heart,0,2,5,40,40,...,,,,,,2014,6,University of Wisconsin Hospital and Clinics (...,,

column_adding['YEAR'].unique()

In [29]:
# column_adding['CTR_CD'] = column_adding['ctr_cd'] + column_adding['CTR_CD']

# column_adding

year_df = column_adding[column_adding['YEAR'] == 2021]
year_df

Empty DataFrame
Columns: [Unnamed: 0,  ctr_cd, ctr_ty, RELEASE_DATE, ORG, GSR_AD_OBS_C1M, GSR_AD_OBS_C1Y, GSR_AD_OBS_C3Y, GSR_AD_N_C1M, GSR_AD_N_C1Y, GSR_AD_N_C3Y, GSR_P0_OBS_C1M, GSR_P0_OBS_C1Y, GSR_P0_OBS_C3Y, GSR_P0_N_C1M, GSR_P0_N_C1Y, YEAR, MONTH, ENTIRE_NAME, CTR_CD, CTR_TY]
Index: []

[0 rows x 21 columns]

In [26]:
column_adding['CTR_CD'] = column_adding['ctr_cd'] + column_adding['CTR_CD']

column_adding

KeyError: 'ctr_cd'