In [9]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.preprocessing import StandardScaler

In [10]:
kidney_df=pd.read_excel(io="merged/KIDNEY_DATA0010625_1.xlsx", sheet_name="1_Year")
kidney_df

,Transplant Year,Age Group,N,Graft_Survival_Rate_1,Patient_Survival_Rate_1,All ABO,O,A,B,AB,...,Retransplant/Graft Failure,Tubular and Interstitial Diseases,"White, Non-Hispanic","Black, Non-Hispanic",Hispanic/Latino,Unknown,"Asian, Non-Hispanic","American Indian/Alaska Native, Non-Hispanic","Pacific Islander, Non-Hispanic","Multiracial, Non-Hispanic"
0,2021,<1 Year,0.0,0.00,0.00,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,130,52,49,0,11,4,0,11
1,2021,1-5 Years,178.0,98.30,99.42,184.0,77.0,74.0,28.0,5.0,...,0.0,8.0,272,94,95,0,36,1,0,13
2,2021,6-10 Years,127.0,97.60,100.00,138.0,75.0,43.0,15.0,5.0,...,5.0,11.0,142,39,88,0,11,2,1,5
3,2021,11-17 Years,444.0,97.49,99.77,497.0,258.0,162.0,59.0,18.0,...,21.0,42.0,383,145,235,0,38,10,4,19
4,2021,18-34,2428.0,97.39,99.36,2975.0,1432.0,992.0,431.0,120.0,...,332.0,116.0,1884,1054,1158,0,217,32,24,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,1988,11-17 Years,271.0,85.19,96.65,407.0,182.0,163.0,44.0,18.0,...,3.0,62.0,356,103,62,3,11,4,0,0
268,1988,18-34,2076.0,86.15,95.63,2794.0,1286.0,1060.0,322.0,125.0,...,10.0,235.0,2419,603,303,3,83,16,7,0
269,1988,35-49,2579.0,83.17,93.57,3289.0,1486.0,1274.0,383.0,146.0,...,8.0,201.0,3196,838,291,5,109,43,1,0
270,1988,50-64,1654.0,80.53,88.41,1926.0,876.0,730.0,232.0,88.0,...,2.0,112.0,2487,490,179,6,60,20,3,0
271,1988,65+,195.0,70.23,78.43,212.0,98.0,80.0,17.0,17.0,...,1.0,11.0,219,28,11,1,4,2,0,0

In [11]:
kidney_df.columns

Index(['Transplant Year', 'Age Group', 'N', 'Graft_Survival_Rate_1 ',
       'Patient_Survival_Rate_1', 'All ABO', 'O', 'A', 'B', 'AB',
       'Deceased Donor', 'Living Donor',
       'Congenital, Rare, Familial, and Metaboli', 'Diabetes',
       'Glomerular Disease', 'Hypertensive Nephrosclerosis', 'Neoplasms',
       'Not Reported', 'Other', 'Polycystic Kidneys',
       'Renovascular and Other Vascular Disease', 'Retransplant/Graft Failure',
       'Tubular and Interstitial Diseases', 'White, Non-Hispanic',
       'Black, Non-Hispanic', 'Hispanic/Latino', 'Unknown',
       'Asian, Non-Hispanic', 'American Indian/Alaska Native, Non-Hispanic',
       'Pacific Islander, Non-Hispanic', 'Multiracial, Non-Hispanic'],
      dtype='object')

In [12]:
for column in kidney_df.columns:
    if column not in ['Transplant Year', 'Age Group']:
        kidney_df[column] = pd.to_numeric(kidney_df[column], errors='coerce')
        
kidney_df.fillna(0,inplace=True)
kidney_df

,Transplant Year,Age Group,N,Graft_Survival_Rate_1,Patient_Survival_Rate_1,All ABO,O,A,B,AB,...,Retransplant/Graft Failure,Tubular and Interstitial Diseases,"White, Non-Hispanic","Black, Non-Hispanic",Hispanic/Latino,Unknown,"Asian, Non-Hispanic","American Indian/Alaska Native, Non-Hispanic","Pacific Islander, Non-Hispanic","Multiracial, Non-Hispanic"
0,2021,<1 Year,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,130,52,49,0,11,4,0,11
1,2021,1-5 Years,178.0,98.30,99.42,184.0,77.0,74.0,28.0,5.0,...,0.0,8.0,272,94,95,0,36,1,0,13
2,2021,6-10 Years,127.0,97.60,100.00,138.0,75.0,43.0,15.0,5.0,...,5.0,11.0,142,39,88,0,11,2,1,5
3,2021,11-17 Years,444.0,97.49,99.77,497.0,258.0,162.0,59.0,18.0,...,21.0,42.0,383,145,235,0,38,10,4,19
4,2021,18-34,2428.0,97.39,99.36,2975.0,1432.0,992.0,431.0,120.0,...,332.0,116.0,1884,1054,1158,0,217,32,24,38
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
267,1988,11-17 Years,271.0,85.19,96.65,407.0,182.0,163.0,44.0,18.0,...,3.0,62.0,356,103,62,3,11,4,0,0
268,1988,18-34,2076.0,86.15,95.63,2794.0,1286.0,1060.0,322.0,125.0,...,10.0,235.0,2419,603,303,3,83,16,7,0
269,1988,35-49,2579.0,83.17,93.57,3289.0,1486.0,1274.0,383.0,146.0,...,8.0,201.0,3196,838,291,5,109,43,1,0
270,1988,50-64,1654.0,80.53,88.41,1926.0,876.0,730.0,232.0,88.0,...,2.0,112.0,2487,490,179,6,60,20,3,0
271,1988,65+,195.0,70.23,78.43,212.0,98.0,80.0,17.0,17.0,...,1.0,11.0,219,28,11,1,4,2,0,0

In [13]:
kidney_df.to_csv("merged/kidney_clean_1.csv")