In [1]:
# importing dependencies

import pandas as pd
import os
import re
import calendar
import numpy as np

In [2]:
# grabbing all the files in the "Resources_HR" directory

excel_files = [file for file in os.listdir("Resources_PA") if not file.startswith("~") and file.lower().endswith(".xls")]

In [3]:
# checking to see that all files were imported

print(len(excel_files))

22

In [4]:


concat=False;
for file in excel_files:
    year_month = re.sub("[^\d]", "", file)
    year = "20"+year_month[0:2]
    month = int(year_month[2:4])
    
    
    if(year in ["2012", "2013", "2014"]):
        sheet_name = "Table 10"
    elif(year in ['2015', '2016', '2017', '2018', '2019', '2020', '2021']):
        sheet_name = "TablesC5-C10 FiguresC1-C12"
    else:
        sheet_name = "TablesC5-C12 Figures C1-C20"
        
    
    survival_df = pd.read_excel(io='Resources_PA/'+file, sheet_name=sheet_name)

        
    if(len(survival_df.index)>0):
        survival_df = survival_df.drop(survival_df.index[0])
   
        
    survival_df_cleaned = pd.DataFrame()
    
    
    
    columns_to_keep = ["Unnamed: 0", ' ctr_cd', 'ctr_ty', 'ENTIRE_NAME', 'CTR_CD', 'CTR_TY', 'RELEASE_DATE', 'ORG', 
                   'GSR_AD_OBS_C1M', 'GSR_AD_OBS_C1Y', 'GSR_AD_OBS_C3Y', 
                   'GSR_AD_N_C1M', 'GSR_AD_N_C1Y', 'GSR_AD_N_C3Y', 
                   'GSR_P0_OBS_C1M', 'GSR_P0_OBS_C1Y', 'GSR_P0_OBS_C3Y', 
                   'GSR_P0_N_C1M', 'GSR_P0_N_C1Y', 'GSR_P0_C3Y']
    
    for column in columns_to_keep:
        if column in survival_df:
            survival_df_cleaned[column]=survival_df[column]
        elif column+" " in survival_df:
            survival_df_cleaned[column]=survival_df[column+" "]
        elif " "+column in survival_df:
            survival_df_cleaned[column]=survival_df[" "+column]
        elif " "+column+" " in survival_df:
            survival_df_cleaned[column]=survival_df[" "+column+" "]

    
    survival_df_cleaned["YEAR"]=year
    survival_df_cleaned["MONTH"]=month

    if(concat==True):
        merged_survival_df= pd.concat([merged_survival_df, survival_df_cleaned], axis=0)

    else:
        merged_survival_df=survival_df_cleaned
        
        concat=True

ValueError: Worksheet named 'Table 10' not found

In [5]:
merged_survival_df

,Unnamed: 0,ctr_cd,ctr_ty,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_N_C1M,GSR_AD_N_C1Y,...,GSR_P0_OBS_C1M,GSR_P0_OBS_C1Y,GSR_P0_OBS_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH,ENTIRE_NAME,CTR_CD,CTR_TY
1,University of South Alabama Medical Center (AL...,ALAM,TX1,2012/07/13,Kidney,,,6,,,...,,,,,,2012,7,NaN,NaN,NaN
2,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Kidney,8,29,71,573,573,...,0,3,6,53,53,2012,7,NaN,NaN,NaN
3,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Kidney,3,8,18,86,86,...,,,,,,2012,7,NaN,NaN,NaN
4,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Kidney,0,0,,2,2,...,0,1,2,19,19,2012,7,NaN,NaN,NaN
5,UAMS Medical Center (ARUA),ARUA,TX1,2012/07/13,Kidney,3,6,30,140,140,...,,,,,,2012,7,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Kidney,0,0,1,6,6,...,0,0,1,18,18,2014,6,NaN,NaN,NaN
244,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Kidney,1,4,26,195,195,...,,,,,,2014,6,NaN,NaN,NaN
245,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Kidney,1,7,10,73,73,...,,,,,,2014,6,NaN,NaN,NaN
246,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Kidney,7,33,80,606,606,...,0,0,0,6,6,2014,6,NaN,NaN,NaN
247,Charleston Area Medical Center (WVCA),WVCA,TX1,2014/06/17,Kidney,2,5,11,98,98,...,1,1,1,4,4,2014,6,NaN,NaN,NaN

In [6]:
column_adding = merged_survival_df.copy()

# df['b'] = df['b'].fillna(df['a'])

column_adding['ENTIRE_NAME'] = column_adding['ENTIRE_NAME'].fillna(column_adding['Unnamed: 0'])

# column_adding['ENTIRE_NAME'] = column_adding['ENTIRE_NAME'] + column_adding['Unnamed: 0']

column_adding

,Unnamed: 0,ctr_cd,ctr_ty,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_N_C1M,GSR_AD_N_C1Y,...,GSR_P0_OBS_C1M,GSR_P0_OBS_C1Y,GSR_P0_OBS_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH,ENTIRE_NAME,CTR_CD,CTR_TY
1,University of South Alabama Medical Center (AL...,ALAM,TX1,2012/07/13,Kidney,,,6,,,...,,,,,,2012,7,University of South Alabama Medical Center (AL...,NaN,NaN
2,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Kidney,8,29,71,573,573,...,0,3,6,53,53,2012,7,University of Alabama Hospital (ALUA),NaN,NaN
3,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Kidney,3,8,18,86,86,...,,,,,,2012,7,Baptist Medical Center (ARBH),NaN,NaN
4,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Kidney,0,0,,2,2,...,0,1,2,19,19,2012,7,Arkansas Children's Hospital (ARCH),NaN,NaN
5,UAMS Medical Center (ARUA),ARUA,TX1,2012/07/13,Kidney,3,6,30,140,140,...,,,,,,2012,7,UAMS Medical Center (ARUA),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Kidney,0,0,1,6,6,...,0,0,1,18,18,2014,6,Children's Hospital of Wisconsin (WICH),NaN,NaN
244,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Kidney,1,4,26,195,195,...,,,,,,2014,6,Froedtert Memorial Lutheran Hospital (WISE),NaN,NaN
245,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Kidney,1,7,10,73,73,...,,,,,,2014,6,Aurora St. Luke's Medical Center (WISL),NaN,NaN
246,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Kidney,7,33,80,606,606,...,0,0,0,6,6,2014,6,University of Wisconsin Hospital and Clinics (...,NaN,NaN
247,Charleston Area Medical Center (WVCA),WVCA,TX1,2014/06/17,Kidney,2,5,11,98,98,...,1,1,1,4,4,2014,6,Charleston Area Medical Center (WVCA),NaN,NaN

In [7]:
column_adding['YEAR'].unique()

array(['2012', '2013', '2018', '2019', '2015', '2021', '2014', '2020',
       '2017', '2022', '2016'], dtype=object)

In [8]:
# df.loc[df['column_name'].isin(some_values)]

column_adding.loc[column_adding['YEAR']=='2012']

,Unnamed: 0,ctr_cd,ctr_ty,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_N_C1M,GSR_AD_N_C1Y,...,GSR_P0_OBS_C1M,GSR_P0_OBS_C1Y,GSR_P0_OBS_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH,ENTIRE_NAME,CTR_CD,CTR_TY
1,University of South Alabama Medical Center (AL...,ALAM,TX1,2012/07/13,Kidney,,,6,,,...,,,,,,2012,7,University of South Alabama Medical Center (AL...,NaN,NaN
2,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Kidney,8,29,71,573,573,...,0,3,6,53,53,2012,7,University of Alabama Hospital (ALUA),NaN,NaN
3,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Kidney,3,8,18,86,86,...,,,,,,2012,7,Baptist Medical Center (ARBH),NaN,NaN
4,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Kidney,0,0,,2,2,...,0,1,2,19,19,2012,7,Arkansas Children's Hospital (ARCH),NaN,NaN
5,UAMS Medical Center (ARUA),ARUA,TX1,2012/07/13,Kidney,3,6,30,140,140,...,,,,,,2012,7,UAMS Medical Center (ARUA),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2012/07/13,Kidney,8,11,24,219,219,...,,,,,,2012,7,Froedtert Memorial Lutheran Hospital (WISE),NaN,NaN
250,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2012/07/13,Kidney,3,5,11,71,71,...,,,,,,2012,7,Aurora St. Luke's Medical Center (WISL),NaN,NaN
251,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2012/07/13,Kidney,8,25,113,590,590,...,0,0,0,15,15,2012,7,University of Wisconsin Hospital and Clinics (...,NaN,NaN
252,Charleston Area Medical Center (WVCA),WVCA,TX1,2012/07/13,Kidney,2,5,15,87,87,...,1,1,0,5,5,2012,7,Charleston Area Medical Center (WVCA),NaN,NaN
253,West Virginia University Hospital (WVWU),WVWU,TX1,2012/07/13,Kidney,,,1,,,...,,,,,,2012,7,West Virginia University Hospital (WVWU),NaN,NaN

In [9]:
column_adding.columns

Index(['Unnamed: 0', ' ctr_cd', 'ctr_ty', 'RELEASE_DATE', 'ORG',
       'GSR_AD_OBS_C1M', 'GSR_AD_OBS_C1Y', 'GSR_AD_OBS_C3Y', 'GSR_AD_N_C1M',
       'GSR_AD_N_C1Y', 'GSR_AD_N_C3Y', 'GSR_P0_OBS_C1M', 'GSR_P0_OBS_C1Y',
       'GSR_P0_OBS_C3Y', 'GSR_P0_N_C1M', 'GSR_P0_N_C1Y', 'YEAR', 'MONTH',
       'ENTIRE_NAME', 'CTR_CD', 'CTR_TY'],
      dtype='object')

In [10]:
# column_adding['ENTIRE_NAME'] = column_adding['ENTIRE_NAME'].fillna(column_adding['Unnamed: 0'])
column_adding['CTR_CD'] = column_adding['CTR_CD'].fillna(column_adding[' ctr_cd'])
column_adding['CTR_TY'] = column_adding['CTR_TY'].fillna(column_adding['ctr_ty'])

column_adding

,Unnamed: 0,ctr_cd,ctr_ty,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_N_C1M,GSR_AD_N_C1Y,...,GSR_P0_OBS_C1M,GSR_P0_OBS_C1Y,GSR_P0_OBS_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH,ENTIRE_NAME,CTR_CD,CTR_TY
1,University of South Alabama Medical Center (AL...,ALAM,TX1,2012/07/13,Kidney,,,6,,,...,,,,,,2012,7,University of South Alabama Medical Center (AL...,ALAM,TX1
2,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Kidney,8,29,71,573,573,...,0,3,6,53,53,2012,7,University of Alabama Hospital (ALUA),ALUA,TX1
3,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Kidney,3,8,18,86,86,...,,,,,,2012,7,Baptist Medical Center (ARBH),ARBH,TX1
4,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Kidney,0,0,,2,2,...,0,1,2,19,19,2012,7,Arkansas Children's Hospital (ARCH),ARCH,TX1
5,UAMS Medical Center (ARUA),ARUA,TX1,2012/07/13,Kidney,3,6,30,140,140,...,,,,,,2012,7,UAMS Medical Center (ARUA),ARUA,TX1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Kidney,0,0,1,6,6,...,0,0,1,18,18,2014,6,Children's Hospital of Wisconsin (WICH),WICH,TX1
244,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Kidney,1,4,26,195,195,...,,,,,,2014,6,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1
245,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Kidney,1,7,10,73,73,...,,,,,,2014,6,Aurora St. Luke's Medical Center (WISL),WISL,TX1
246,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Kidney,7,33,80,606,606,...,0,0,0,6,6,2014,6,University of Wisconsin Hospital and Clinics (...,WIUW,TX1
247,Charleston Area Medical Center (WVCA),WVCA,TX1,2014/06/17,Kidney,2,5,11,98,98,...,1,1,1,4,4,2014,6,Charleston Area Medical Center (WVCA),WVCA,TX1

In [11]:
column_adding.loc[column_adding['YEAR']=='2021']

,Unnamed: 0,ctr_cd,ctr_ty,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_N_C1M,GSR_AD_N_C1Y,...,GSR_P0_OBS_C1M,GSR_P0_OBS_C1Y,GSR_P0_OBS_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH,ENTIRE_NAME,CTR_CD,CTR_TY
1,NaN,NaN,NaN,2021-07-06 19:00:00,KI,NaN,NaN,NaN,NaN,NaN,...,0,0,0,24,24,2021,5,Children's of Alabama (ALCH),ALCH,TX1
2,NaN,NaN,NaN,2021-07-06 19:00:00,KI,2,14,37,572,572,...,0,0,NaN,1,1,2021,5,University of Alabama Hospital (ALUA),ALUA,TX1
3,NaN,NaN,NaN,2021-07-06 19:00:00,KI,0,0,0,15,15,...,NaN,NaN,NaN,NaN,NaN,2021,5,Birmingham VA Medical Center (ALVA),ALVA,TX1
4,NaN,NaN,NaN,2021-07-06 19:00:00,KI,NaN,NaN,NaN,NaN,NaN,...,0,0,0,19,19,2021,5,Arkansas Children's Hospital (ARCH),ARCH,TX1
5,NaN,NaN,NaN,2021-07-06 19:00:00,KI,0,7,15,301,301,...,NaN,NaN,NaN,NaN,NaN,2021,5,UAMS Medical Center (ARUA),ARUA,TX1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,NaN,NaN,NaN,2022-01-06 18:00:00,KI,1,5,15,138,138,...,NaN,NaN,NaN,NaN,NaN,2021,11,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1
234,NaN,NaN,NaN,2022-01-06 18:00:00,KI,0,0,3,91,91,...,NaN,NaN,NaN,NaN,NaN,2021,11,Aurora St. Luke's Medical Center (WISL),WISL,TX1
235,NaN,NaN,NaN,2022-01-06 18:00:00,KI,7,25,46,670,670,...,0,0,0,11,11,2021,11,University of Wisconsin Hospital and Clinics (...,WIUW,TX1
236,NaN,NaN,NaN,2022-01-06 18:00:00,KI,4,11,7,205,205,...,NaN,NaN,0,NaN,NaN,2021,11,Charleston Area Medical Center (WVCA),WVCA,TX1
237,NaN,NaN,NaN,2022-01-06 18:00:00,KI,0,0,NaN,6,6,...,NaN,NaN,NaN,NaN,NaN,2021,11,West Virginia University Hospital (WVWU),WVWU,TX1

In [12]:
survival_final = column_adding.drop(columns=['Unnamed: 0', ' ctr_cd', 'ctr_ty'])

survival_final

,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_N_C1M,GSR_AD_N_C1Y,GSR_AD_N_C3Y,GSR_P0_OBS_C1M,GSR_P0_OBS_C1Y,GSR_P0_OBS_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH,ENTIRE_NAME,CTR_CD,CTR_TY
1,2012/07/13,Kidney,,,6,,,21,,,,,,2012,7,University of South Alabama Medical Center (AL...,ALAM,TX1
2,2012/07/13,Kidney,8,29,71,573,573,659,0,3,6,53,53,2012,7,University of Alabama Hospital (ALUA),ALUA,TX1
3,2012/07/13,Kidney,3,8,18,86,86,93,,,,,,2012,7,Baptist Medical Center (ARBH),ARBH,TX1
4,2012/07/13,Kidney,0,0,,2,2,,0,1,2,19,19,2012,7,Arkansas Children's Hospital (ARCH),ARCH,TX1
5,2012/07/13,Kidney,3,6,30,140,140,155,,,,,,2012,7,UAMS Medical Center (ARUA),ARUA,TX1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,2014/06/17,Kidney,0,0,1,6,6,2,0,0,1,18,18,2014,6,Children's Hospital of Wisconsin (WICH),WICH,TX1
244,2014/06/17,Kidney,1,4,26,195,195,241,,,,,,2014,6,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1
245,2014/06/17,Kidney,1,7,10,73,73,69,,,,,,2014,6,Aurora St. Luke's Medical Center (WISL),WISL,TX1
246,2014/06/17,Kidney,7,33,80,606,606,594,0,0,0,6,6,2014,6,University of Wisconsin Hospital and Clinics (...,WIUW,TX1
247,2014/06/17,Kidney,2,5,11,98,98,85,1,1,1,4,4,2014,6,Charleston Area Medical Center (WVCA),WVCA,TX1

In [13]:
first_column = survival_final.pop('ENTIRE_NAME')
second_column = survival_final.pop('CTR_CD')
third_column = survival_final.pop('CTR_TY')

survival_final.insert(0, 'ENTIRE_NAME', first_column)
survival_final.insert(1, 'CTR_CD', second_column)
survival_final.insert(2, 'CTR_TY', third_column)

survival_final

,ENTIRE_NAME,CTR_CD,CTR_TY,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_N_C1M,GSR_AD_N_C1Y,GSR_AD_N_C3Y,GSR_P0_OBS_C1M,GSR_P0_OBS_C1Y,GSR_P0_OBS_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH
1,University of South Alabama Medical Center (AL...,ALAM,TX1,2012/07/13,Kidney,,,6,,,21,,,,,,2012,7
2,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Kidney,8,29,71,573,573,659,0,3,6,53,53,2012,7
3,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Kidney,3,8,18,86,86,93,,,,,,2012,7
4,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Kidney,0,0,,2,2,,0,1,2,19,19,2012,7
5,UAMS Medical Center (ARUA),ARUA,TX1,2012/07/13,Kidney,3,6,30,140,140,155,,,,,,2012,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Kidney,0,0,1,6,6,2,0,0,1,18,18,2014,6
244,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Kidney,1,4,26,195,195,241,,,,,,2014,6
245,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Kidney,1,7,10,73,73,69,,,,,,2014,6
246,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Kidney,7,33,80,606,606,594,0,0,0,6,6,2014,6
247,Charleston Area Medical Center (WVCA),WVCA,TX1,2014/06/17,Kidney,2,5,11,98,98,85,1,1,1,4,4,2014,6

In [14]:
final_df = survival_final.copy()
final_df

,ENTIRE_NAME,CTR_CD,CTR_TY,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_N_C1M,GSR_AD_N_C1Y,GSR_AD_N_C3Y,GSR_P0_OBS_C1M,GSR_P0_OBS_C1Y,GSR_P0_OBS_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH
1,University of South Alabama Medical Center (AL...,ALAM,TX1,2012/07/13,Kidney,,,6,,,21,,,,,,2012,7
2,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Kidney,8,29,71,573,573,659,0,3,6,53,53,2012,7
3,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Kidney,3,8,18,86,86,93,,,,,,2012,7
4,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Kidney,0,0,,2,2,,0,1,2,19,19,2012,7
5,UAMS Medical Center (ARUA),ARUA,TX1,2012/07/13,Kidney,3,6,30,140,140,155,,,,,,2012,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Kidney,0,0,1,6,6,2,0,0,1,18,18,2014,6
244,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Kidney,1,4,26,195,195,241,,,,,,2014,6
245,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Kidney,1,7,10,73,73,69,,,,,,2014,6
246,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Kidney,7,33,80,606,606,594,0,0,0,6,6,2014,6
247,Charleston Area Medical Center (WVCA),WVCA,TX1,2014/06/17,Kidney,2,5,11,98,98,85,1,1,1,4,4,2014,6

In [16]:
final_df.to_csv("Resources/KI_survival.csv", index=False, header=True)