In [1]:
# Importing dependencies

import pandas as pd
import os
import re
import calendar
import numpy as np

In [2]:
KI_file = "Resources/kidney_concat.csv"
LU_file = "Resources/LU_transplant_all.csv"
HR_file = "Resources/final_center_heart.csv"
LI_file = "Resources/LI_transplant_all.csv"

In [3]:
KI_df = pd.read_csv(KI_file)
KI_df

,Unnamed: 0,ENTIRE_NAME,CTR_CD,CTR_TY,RELEASE_DATE,ORG,RCC_A10_C,RCC_A17_C,RCC_A2_C,RCC_A34_C,...,RCC_HOSPNR_C,RCC_HOSP_C,RCC_PTXN_C,RCC_PTXU_C,RCC_PTXY_C,RCC_NOTHOSP_C,RCC_N_C,YEAR,MONTH,D_OR_L
0,0,Children's of Alabama (ALCH),ALCH,TX1,2015/06/16,Kidney,20.000000,53.3,6.7,20.000000,...,0.0,6.7,93.300000,0.0,6.700000,93.3,15,2015.0,6.0,DECEASED
1,1,University of Alabama Hospital (ALUA),ALUA,TX1,2015/06/16,Kidney,0.000000,0.0,0.0,11.300000,...,0.0,0.8,84.700000,0.0,15.300000,97.6,124,2015.0,6.0,DECEASED
2,2,Baptist Medical Center (ARBH),ARBH,TX1,2015/06/16,Kidney,0.000000,0.0,0.0,0.000000,...,0.0,19.0,95.200000,0.0,4.800000,81.0,21,2015.0,6.0,DECEASED
3,3,Arkansas Children's Hospital (ARCH),ARCH,TX1,2015/06/16,Kidney,66.700000,33.3,0.0,0.000000,...,0.0,0.0,83.300000,0.0,16.700000,100.0,6,2015.0,6.0,DECEASED
4,4,UAMS Medical Center (ARUA),ARUA,TX1,2015/06/16,Kidney,0.000000,0.0,0.0,30.000000,...,0.0,0.0,90.000000,0.0,10.000000,100.0,30,2015.0,6.0,DECEASED
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10065,216,University of Virginia Health Sciences Center ...,VAUV,TX1,2023-01-05 18:00:00,KI,3.571429,0.0,0.0,10.714286,...,100.0,0.0,89.285714,0.0,10.714286,0.0,28,2022.0,11.0,LIVING
10066,217,NaN,ILVA,TX1,2023-01-05 18:00:00,KI,0.000000,0.0,0.0,0.000000,...,100.0,0.0,100.000000,0.0,0.000000,0.0,1,2022.0,11.0,LIVING
10067,218,NaN,PARH,TX1,2023-01-05 18:00:00,KI,0.000000,0.0,0.0,100.000000,...,100.0,0.0,100.000000,0.0,0.000000,0.0,1,2022.0,11.0,LIVING
10068,219,NaN,SCPG,TX1,2023-01-05 18:00:00,KI,0.000000,0.0,0.0,0.000000,...,100.0,0.0,75.000000,0.0,25.000000,0.0,4,2022.0,11.0,LIVING
10069,220,NaN,TXDS,TX1,2023-01-05 18:00:00,KI,0.000000,0.0,0.0,16.666667,...,100.0,0.0,100.000000,0.0,0.000000,0.0,6,2022.0,11.0,LIVING

In [4]:
LU_df = pd.read_csv(LU_file)
LU_df

,ENTIRE_NAME,CTR_CD,CTR_TY,RELEASE_DATE,ORG,RCC_A10_C,RCC_A17_C,RCC_A2_C,RCC_A34_C,RC_A49_C,...,RCC_ICU_C,RCC_HOSPNR_C,RCC_HOSP_C,RCC_PTXN_C,RCC_PTXU_C,RCC_PTXY_C,RCC_TINA_R,D_OR_L,YEAR,MONTH
0,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Lung,0.0,0.0,0.0,26.100000,13.000000,...,17.4,0.000000,91.300000,0.0,8.700000,56.500000,52.200000,D,2012,7
1,St. Joseph's Hospital and Medical Center (AZSJ),AZSJ,TX1,2012/07/13,Lung,0.0,0.0,0.0,11.900000,16.700000,...,0.0,4.800000,88.100000,0.0,11.900000,85.700000,38.100000,D,2012,7
2,"University Medical Center, Univ of Arizona (AZ...",AZUA,TX1,2012/07/13,Lung,3.8,0.0,0.0,19.200000,19.200000,...,0.0,3.800000,92.300000,0.0,7.700000,76.900000,46.200000,D,2012,7
3,Cedars-Sinai Medical Center (CACS),CACS,TX1,2012/07/13,Lung,0.0,0.0,0.0,6.700000,0.000000,...,0.0,20.000000,86.700000,0.0,13.300000,73.300000,46.700000,D,2012,7
4,Lucile Salter Packard Children's Hospital at S...,CAPC,TX1,2012/07/13,Lung,0.0,33.3,0.0,66.700000,0.000000,...,0.0,0.000000,100.000000,0.0,0.000000,100.000000,0.000000,D,2012,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1481,Duke University Hospital (NCDU),NCDU,TX1,2023-01-05 18:00:00,LU,0.0,0.0,0.0,3.571429,8.035714,...,0.0,10.714286,92.857143,0.0,7.142857,85.714286,48.214286,D,2022,11
1482,University of North Carolina Hospitals (NCMH),NCMH,TX1,2023-01-05 18:00:00,LU,0.0,0.0,0.0,0.000000,33.333333,...,0.0,11.111111,100.000000,0.0,0.000000,66.666667,33.333333,D,2022,11
1483,Medical University of South Carolina (SCMU),SCMU,TX1,2023-01-05 18:00:00,LU,0.0,0.0,0.0,0.000000,0.000000,...,0.0,9.090909,100.000000,0.0,0.000000,63.636364,36.363636,D,2022,11
1484,Vanderbilt University Medical Center (TNVU),TNVU,TX1,2023-01-05 18:00:00,LU,0.0,0.0,0.0,3.225806,6.451613,...,0.0,12.903226,98.387097,0.0,1.612903,75.806452,58.064516,D,2022,11
1485,University of Virginia Health Sciences Center ...,VAUV,TX1,2023-01-05 18:00:00,LU,0.0,0.0,0.0,3.571429,3.571429,...,0.0,14.285714,100.000000,0.0,0.000000,57.142857,50.000000,D,2022,11

In [5]:
HR_df = pd.read_csv(HR_file)

HR_df

,Unnamed: 0,ENTIRE_NAME,CTR_CD,CTR_TY,RELEASE_DATE,ORG,RCC_A10_C,RCC_A17_C,RCC_A2_C,RCC_A34_C,...,RCC_TINA_C,RCC_TINA_R,RCC_N_C,RCC_DEVS_C,RCC_NOTLS_C,RCC_LS_C,RCC_LSNR_C,D_OR_L,YEAR,MONTH
0,1,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Heart,15.6,15.6,0.0,3.1,...,0.0,0.0,32,28.1,25.0,40.6,6.3,D,2012,July
1,2,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Heart,0.0,0.0,0.0,12.5,...,0.0,0.0,8,37.5,12.5,50.0,0.0,D,2012,July
2,3,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Heart,32.3,19.4,48.4,0.0,...,0.0,0.0,31,32.3,9.7,58.1,0.0,D,2012,July
3,4,Phoenix Children's Hospital (AZCH),AZCH,TX1,2012/07/13,Heart,0.0,50.0,50.0,0.0,...,0.0,0.0,2,0.0,100.0,0.0,0.0,D,2012,July
4,5,Mayo Clinic Hospital (AZMC),AZMC,TX1,2012/07/13,Heart,0.0,0.0,0.0,0.0,...,0.0,0.0,14,71.4,0.0,28.6,0.0,D,2012,July
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2945,122,University of Washington Medical Center (WAUW),WAUW,TX1,2014/06/17,Heart,0.0,0.0,0.0,17.2,...,0.0,0.0,29,79.3,13.8,6.9,0.0,D,2014,June
2946,123,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Heart,20.0,10.0,50.0,20.0,...,0.0,0.0,10,30.0,20.0,50.0,0.0,D,2014,June
2947,124,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Heart,0.0,0.0,0.0,14.3,...,0.0,0.0,7,71.4,28.6,0.0,0.0,D,2014,June
2948,125,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Heart,0.0,0.0,0.0,0.0,...,0.0,0.0,22,72.7,22.7,0.0,4.5,D,2014,June
2949,126,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Heart,0.0,0.0,0.0,0.0,...,0.0,0.0,26,88.5,11.5,0.0,0.0,D,2014,June

In [6]:
LI_df = pd.read_csv(LI_file)
LI_df

,Unnamed: 0,ENTIRE_NAME,CTR_CD,CTR_TY,RELEASE_DATE,ORG,RCC_A10_C,RCC_A17_C,RCC_A2_C,RCC_A34_C,...,RCC_TINA_C,RCC_TINA_R,RCC_N_C,D_OR_L,YEAR,MONTH,RCC_A65P_C,RCC_AU_C,RCC_BMI31P_C,RCC_TST1B_R
0,1,Hartford Hospital (CTHH),CTHH,TX1,2021-01-04 18:00:00,LI,0.000000,0.000000,0.000000,5.263158,...,0.0,0.0,19.0,D,2020,November,NaN,NaN,NaN,NaN
1,2,Yale New Haven Hospital (CTYN),CTYN,TX1,2021-01-04 18:00:00,LI,0.000000,5.263158,0.000000,0.000000,...,0.0,0.0,19.0,D,2020,November,NaN,NaN,NaN,NaN
2,3,Beth Israel Deaconess Medical Center (MABI),MABI,TX1,2021-01-04 18:00:00,LI,0.000000,0.000000,0.000000,13.157895,...,0.0,0.0,38.0,D,2020,November,NaN,NaN,NaN,NaN
3,4,Boston Children's Hospital (MACH),MACH,TX1,2021-01-04 18:00:00,LI,33.333333,16.666667,33.333333,16.666667,...,0.0,0.0,6.0,D,2020,November,NaN,NaN,NaN,NaN
4,5,Lahey Clinic Medical Center (MALC),MALC,TX1,2021-01-04 18:00:00,LI,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,57.0,D,2020,November,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4155,57,Duke University Hospital (NCDU),NCDU,TX1,2022-07-06 19:00:00,LI,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,L,2022,May,NaN,NaN,NaN,NaN
4156,58,Methodist University Hospital (TNMH),TNMH,TX1,2022-07-06 19:00:00,LI,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,L,2022,May,NaN,NaN,NaN,NaN
4157,59,Vanderbilt University Medical Center (TNVU),TNVU,TX1,2022-07-06 19:00:00,LI,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,L,2022,May,NaN,NaN,NaN,NaN
4158,60,Medical College of Virginia Hospitals (VAMC),VAMC,TX1,2022-07-06 19:00:00,LI,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,L,2022,May,NaN,NaN,NaN,NaN
4159,61,University of Virginia Health Sciences Center ...,VAUV,TX1,2022-07-06 19:00:00,LI,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,L,2022,May,NaN,NaN,NaN,NaN

In [7]:
org_all = pd.concat([LI_df, LU_df, KI_df, HR_df], axis=0)
org_all

,Unnamed: 0,ENTIRE_NAME,CTR_CD,CTR_TY,RELEASE_DATE,ORG,RCC_A10_C,RCC_A17_C,RCC_A2_C,RCC_A34_C,...,RCC_BMI31P_C,RCC_TST1B_R,RC_A49_C,RCC_TST1B_R,RCC_TST2_C,RCC_TST2_R,RCC_DEVS_C,RCC_NOTLS_C,RCC_LS_C,RCC_LSNR_C
0,1.0,Hartford Hospital (CTHH),CTHH,TX1,2021-01-04 18:00:00,LI,0.000000,0.000000,0.000000,5.263158,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Yale New Haven Hospital (CTYN),CTYN,TX1,2021-01-04 18:00:00,LI,0.000000,5.263158,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Beth Israel Deaconess Medical Center (MABI),MABI,TX1,2021-01-04 18:00:00,LI,0.000000,0.000000,0.000000,13.157895,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Boston Children's Hospital (MACH),MACH,TX1,2021-01-04 18:00:00,LI,33.333333,16.666667,33.333333,16.666667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Lahey Clinic Medical Center (MALC),MALC,TX1,2021-01-04 18:00:00,LI,0.000000,0.000000,0.000000,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2945,122.0,University of Washington Medical Center (WAUW),WAUW,TX1,2014/06/17,Heart,0.000000,0.000000,0.000000,17.200000,...,37.9,NaN,NaN,38.7,10.3,5.3,79.3,13.8,6.9,0.0
2946,123.0,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Heart,20.000000,10.000000,50.000000,20.000000,...,0.0,NaN,NaN,25.2,0.0,0.4,30.0,20.0,50.0,0.0
2947,124.0,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Heart,0.000000,0.000000,0.000000,14.300000,...,0.0,NaN,NaN,25.2,0.0,0.4,71.4,28.6,0.0,0.0
2948,125.0,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Heart,0.000000,0.000000,0.000000,0.000000,...,50.0,NaN,NaN,25.2,4.5,0.4,72.7,22.7,0.0,4.5
2949,126.0,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Heart,0.000000,0.000000,0.000000,0.000000,...,23.1,NaN,NaN,25.2,0.0,0.4,88.5,11.5,0.0,0.0

In [8]:
org_drop = org_all.drop(columns=['Unnamed: 0'])

org_drop

,ENTIRE_NAME,CTR_CD,CTR_TY,RELEASE_DATE,ORG,RCC_A10_C,RCC_A17_C,RCC_A2_C,RCC_A34_C,RCC_A49_C,...,RCC_BMI31P_C,RCC_TST1B_R,RC_A49_C,RCC_TST1B_R,RCC_TST2_C,RCC_TST2_R,RCC_DEVS_C,RCC_NOTLS_C,RCC_LS_C,RCC_LSNR_C
0,Hartford Hospital (CTHH),CTHH,TX1,2021-01-04 18:00:00,LI,0.000000,0.000000,0.000000,5.263158,10.526316,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Yale New Haven Hospital (CTYN),CTYN,TX1,2021-01-04 18:00:00,LI,0.000000,5.263158,0.000000,0.000000,26.315789,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Beth Israel Deaconess Medical Center (MABI),MABI,TX1,2021-01-04 18:00:00,LI,0.000000,0.000000,0.000000,13.157895,7.894737,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Boston Children's Hospital (MACH),MACH,TX1,2021-01-04 18:00:00,LI,33.333333,16.666667,33.333333,16.666667,0.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Lahey Clinic Medical Center (MALC),MALC,TX1,2021-01-04 18:00:00,LI,0.000000,0.000000,0.000000,0.000000,22.807018,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2945,University of Washington Medical Center (WAUW),WAUW,TX1,2014/06/17,Heart,0.000000,0.000000,0.000000,17.200000,NaN,...,37.9,NaN,NaN,38.7,10.3,5.3,79.3,13.8,6.9,0.0
2946,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Heart,20.000000,10.000000,50.000000,20.000000,NaN,...,0.0,NaN,NaN,25.2,0.0,0.4,30.0,20.0,50.0,0.0
2947,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Heart,0.000000,0.000000,0.000000,14.300000,NaN,...,0.0,NaN,NaN,25.2,0.0,0.4,71.4,28.6,0.0,0.0
2948,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Heart,0.000000,0.000000,0.000000,0.000000,NaN,...,50.0,NaN,NaN,25.2,4.5,0.4,72.7,22.7,0.0,4.5
2949,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Heart,0.000000,0.000000,0.000000,0.000000,NaN,...,23.1,NaN,NaN,25.2,0.0,0.4,88.5,11.5,0.0,0.0

In [9]:
for col in org_drop.columns:
    if col != 'ENTIRE_NAME':
        org_drop[col].fillna(0, inplace=True)
        
org_drop

,ENTIRE_NAME,CTR_CD,CTR_TY,RELEASE_DATE,ORG,RCC_A10_C,RCC_A17_C,RCC_A2_C,RCC_A34_C,RCC_A49_C,...,RCC_BMI31P_C,RCC_TST1B_R,RC_A49_C,RCC_TST1B_R,RCC_TST2_C,RCC_TST2_R,RCC_DEVS_C,RCC_NOTLS_C,RCC_LS_C,RCC_LSNR_C
0,Hartford Hospital (CTHH),CTHH,TX1,2021-01-04 18:00:00,LI,0.000000,0.000000,0.000000,5.263158,10.526316,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Yale New Haven Hospital (CTYN),CTYN,TX1,2021-01-04 18:00:00,LI,0.000000,5.263158,0.000000,0.000000,26.315789,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Beth Israel Deaconess Medical Center (MABI),MABI,TX1,2021-01-04 18:00:00,LI,0.000000,0.000000,0.000000,13.157895,7.894737,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Boston Children's Hospital (MACH),MACH,TX1,2021-01-04 18:00:00,LI,33.333333,16.666667,33.333333,16.666667,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Lahey Clinic Medical Center (MALC),MALC,TX1,2021-01-04 18:00:00,LI,0.000000,0.000000,0.000000,0.000000,22.807018,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2945,University of Washington Medical Center (WAUW),WAUW,TX1,2014/06/17,Heart,0.000000,0.000000,0.000000,17.200000,0.000000,...,37.9,0.0,0.0,38.7,10.3,5.3,79.3,13.8,6.9,0.0
2946,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Heart,20.000000,10.000000,50.000000,20.000000,0.000000,...,0.0,0.0,0.0,25.2,0.0,0.4,30.0,20.0,50.0,0.0
2947,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Heart,0.000000,0.000000,0.000000,14.300000,0.000000,...,0.0,0.0,0.0,25.2,0.0,0.4,71.4,28.6,0.0,0.0
2948,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Heart,0.000000,0.000000,0.000000,0.000000,0.000000,...,50.0,0.0,0.0,25.2,4.5,0.4,72.7,22.7,0.0,4.5
2949,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Heart,0.000000,0.000000,0.000000,0.000000,0.000000,...,23.1,0.0,0.0,25.2,0.0,0.4,88.5,11.5,0.0,0.0

In [10]:
org_all = org_drop

In [11]:
org_all['RCC_TST1B_R'] = org_all['RCC_TST1B_R'] + org_all['RCC_TST1B_R']

In [12]:
org_all.to_csv("Resources/transplant_sql_data.csv", index=False, header=True)

In [12]:
KI_files = "Resources/KI_survival.csv"
LU_files = "Resources/LU_survival.csv"
HR_files = "Resources/HR_survival.csv"
LI_files = "Resources/LI_survival.csv"

In [13]:
KI_s = pd.read_csv(KI_files)
LU_s = pd.read_csv(LU_files)
HR_s = pd.read_csv(HR_files)
LI_s = pd.read_csv(LI_files)

In [14]:
survival_all = pd.concat([LI_s, LU_s, KI_s, HR_s], axis=0)

survival_all

,ENTIRE_NAME,CTR_CD,CTR_TY,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_ACT_C1M,GSR_AD_ACT_C1Y,...,GSR_P0_ADJ_C1Y,GSR_P0_ADJ_C3Y,GSR_P0_EXP_C1M,GSR_P0_EXP_C1Y,GSR_P0_EXP_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH,GSR_P0_ACT_C3Y
0,Children's of Alabama (ALCH),ALCH,TX1,2021-01-04 18:00:00,LI,0,0,0,0,0,...,93.1078232539011,88.5065360511809,0.55447383478861,0.929710380364001,1.37687217717271,14,14,2020,11,NaN
1,University of Alabama Hospital (ALUA),ALUA,TX1,2021-01-04 18:00:00,LI,13,20,41,95.4225352112676,92.7219061145721,...,0,0,0,0,0,0,0,2020,11,NaN
2,UAMS Medical Center (ARUA),ARUA,TX1,2021-01-04 18:00:00,LI,1,4,8,98.9010989010989,95.1941391941392,...,0,0,0,0,0,0,0,2020,11,NaN
3,Phoenix Children's Hospital (AZCH),AZCH,TX1,2021-01-04 18:00:00,LI,0,0,0,0,0,...,91.4858573515557,88.5065360511809,0.906557088021326,1.54948708486219,1.34096683584363,18,18,2020,11,NaN
4,Banner-University Medical Center Phoenix (AZGS),AZGS,TX1,2021-01-04 18:00:00,LI,10,29,28,96.4788732394366,88.5964489488621,...,0,0,0,0,0,0,0,2020,11,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3044,University of Washington Medical Center (WAUW),WAUW,TX1,2014/06/17,Heart,7,7,5,85.71,85.71,...,0,85.32,0,0,0.16,0,0,2014,6,NaN
3045,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Heart,0,1,3,100,87.5,...,89.22,83.06,1.32,3.39,5.16,36,36,2014,6,NaN
3046,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Heart,0,0,0,100,100,...,0,0,0,0,0,0,0,2014,6,NaN
3047,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Heart,0,5,15,100,94.2,...,0,0,0,0,0,0,0,2014,6,NaN
3048,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Heart,0,2,5,100,94.02,...,0,0,0,0,0,0,0,2014,6,NaN

In [15]:
survival_all.to_csv("Resources/survival_sql_data.csv", index=False, header=True)