In [1]:
# importing dependencies

import pandas as pd
import os
import re
import calendar
import numpy as np

In [2]:
# grabbing all the files in the "Resources_HR" directory

excel_files = [file for file in os.listdir("Resources_HR") if not file.startswith("~") and file.lower().endswith(".xls")]

In [3]:
# checking to see that all files were imported

print(len(excel_files))

22

In [4]:


concat=False;
for file in excel_files:
    year_month = re.sub("[^\d]", "", file)
    year = "20"+year_month[0:2]
    month = int(year_month[2:4])
    
    
    if(year in ["2012", "2013", "2014"]):
        sheet_name = "Table 10"
    elif(year in ['2015', '2016', '2017', '2018', '2019', '2020', '2021']):
        sheet_name = "TablesC5-C10 FiguresC1-C12"
    else:
        sheet_name = "TablesC5-C12 Figures C1-C20"
        
    
    survival_df = pd.read_excel(io='Resources_HR/'+file, sheet_name=sheet_name)
#     deceased_nation_df = pd.read_excel(io="Resources_LU/"+file, sheet_name=sheet_name+" - Deceased Nation")
#     living_df = pd.read_excel(io="Resources_LU/"+file, sheet_name=sheet_name+" - Living")
#     living_nation_df = pd.read_excel(io="Resources_LU/"+file, sheet_name=sheet_name+" - Living Nation")
        
    if(len(survival_df.index)>0):
        survival_df = survival_df.drop(survival_df.index[0])
#     if(len(deceased_nation_df.index)>0):
#         deceased_nation_df = deceased_nation_df.drop(deceased_nation_df.index[0])
#     if(len(living_df.index)>0):
#         living_df = living_df.drop(living_df.index[0])
#     if(len(living_nation_df.index)>0):
#         living_nation_df = living_nation_df.drop(living_nation_df.index[0])
        
    survival_df_cleaned = pd.DataFrame()
#     living_df_cleaned = pd.DataFrame()
    
    
    columns_to_keep = ["Unnamed: 0", ' ctr_cd', 'ctr_ty', 'ENTIRE_NAME', 'CTR_CD', 'CTR_TY', 'RELEASE_DATE', 'ORG', 
                       'GSR_AD_OBS_C1M', 'GSR_AD_OBS_C1Y', 'GSR_AD_OBS_C3Y', 
                       'GSR_AD_ACT_C1M', 'GSR_AD_ACT_C1Y', 'GSR_AD_ACT_C3Y', 
                       'GSR_AD_ADJ_C1M', 'GSR_AD_ADJ_C1Y', 'GSR_AD_ADJ_C3Y',
                       'GSR_AD_EXP_C1M', 'GSR_AD_EXP_C1Y', 'GSR_AD_EXP_C3Y', 
                       'GSR_AD_N_C1M', 'GSR_AD_N_C1Y', 'GSR_AD_N_C3Y', 
                       'GSR_P0_OBS_C1M', 'GSR_P0_OBS_C1Y', 'GSR_P0_OBS_C3Y',
                       'GSR_P0_ACT_C1M', 'GSR_P0_ACT_C1Y', 'GSR_P0_ACT_C1Y', 
                       'GSR_P0_ADJ_C1M', 'GSR_P0_ADJ_C1Y', 'GSR_P0_ADJ_C3Y',
                       'GSR_P0_EXP_C1M', 'GSR_P0_EXP_C1Y', 'GSR_P0_EXP_C3Y', 
                       'GSR_P0_N_C1M', 'GSR_P0_N_C1Y', 'GSR_P0_C3Y']
    
    
    for column in columns_to_keep:
        if column in survival_df:
            survival_df_cleaned[column]=survival_df[column]
        elif column+" " in survival_df:
            survival_df_cleaned[column]=survival_df[column+" "]
        elif " "+column in survival_df:
            survival_df_cleaned[column]=survival_df[" "+column]
        elif " "+column+" " in survival_df:
            survival_df_cleaned[column]=survival_df[" "+column+" "]
            
#         if column in living_df:
#             living_df_cleaned[column]=living_df[column]
#         elif column+" " in living_df:
#             living_df_cleaned[column]=living_df[column+" "]
#         elif " "+column in living_df:
#             living_df_cleaned[column]=living_df[" "+column]
#         elif " "+column+" " in living_df:
#             living_df_cleaned[column]=living_df[" "+column+" "]

#     deceased_df_cleaned["D_OR_L"] = "D"
#     deceased_nation_df["D_OR_L"] = "D"
#     living_df_cleaned["D_OR_L"] = "L"
#     living_nation_df["D_OR_L"] = "L"
    
#     center_df = pd.concat([deceased_df_cleaned, living_df_cleaned], axis=0)
#     nation_df = pd.concat([deceased_nation_df, living_nation_df], axis=0)
    
    survival_df_cleaned["YEAR"]=year
    survival_df_cleaned["MONTH"]=month
#     nation_df["YEAR"]=year
#     nation_df["MONTH"]=month
    
    if(concat==True):
        merged_survival_df= pd.concat([merged_survival_df, survival_df_cleaned], axis=0)
#         merged_nation_df= pd.concat([merged_nation_df, nation_df], axis=0)
    else:
        merged_survival_df=survival_df_cleaned
#         merged_nation_df=nation_df
        concat=True

In [5]:
merged_survival_df

,Unnamed: 0,ctr_cd,ctr_ty,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_ACT_C1M,GSR_AD_ACT_C1Y,...,GSR_P0_EXP_C1M,GSR_P0_EXP_C1Y,GSR_P0_EXP_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH,ENTIRE_NAME,CTR_CD,CTR_TY
1,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Heart,0,2,12,100,94.51,...,0.32,0.80,1.69,13,13,2012,7,NaN,NaN,NaN
2,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Heart,0,2,10,100,89.95,...,,,,,,2012,7,NaN,NaN,NaN
3,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Heart,0,0,,100,100,...,3.47,7.92,11.99,51,51,2012,7,NaN,NaN,NaN
4,UAMS Medical Center (ARUA),ARUA,TX1,2012/07/13,Heart,,,0,,,...,,,,,,2012,7,NaN,NaN,NaN
5,Mayo Clinic Hospital (AZMC),AZMC,TX1,2012/07/13,Heart,1,2,8,97.56,94.77,...,,,,,,2012,7,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,University of Washington Medical Center (WAUW),WAUW,TX1,2014/06/17,Heart,7,7,5,85.71,85.71,...,,,0.16,,,2014,6,NaN,NaN,NaN
132,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Heart,0,1,3,100,87.5,...,1.32,3.39,5.16,36,36,2014,6,NaN,NaN,NaN
133,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Heart,0,0,0,100,100,...,,,,,,2014,6,NaN,NaN,NaN
134,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Heart,0,5,15,100,94.2,...,,,,,,2014,6,NaN,NaN,NaN
135,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Heart,0,2,5,100,94.02,...,,,,,,2014,6,NaN,NaN,NaN

In [6]:
column_adding = merged_survival_df.copy()

# df['b'] = df['b'].fillna(df['a'])

column_adding['ENTIRE_NAME'] = column_adding['ENTIRE_NAME'].fillna(column_adding['Unnamed: 0'])

# column_adding['ENTIRE_NAME'] = column_adding['ENTIRE_NAME'] + column_adding['Unnamed: 0']

column_adding

,Unnamed: 0,ctr_cd,ctr_ty,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_ACT_C1M,GSR_AD_ACT_C1Y,...,GSR_P0_EXP_C1M,GSR_P0_EXP_C1Y,GSR_P0_EXP_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH,ENTIRE_NAME,CTR_CD,CTR_TY
1,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Heart,0,2,12,100,94.51,...,0.32,0.80,1.69,13,13,2012,7,University of Alabama Hospital (ALUA),NaN,NaN
2,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Heart,0,2,10,100,89.95,...,,,,,,2012,7,Baptist Medical Center (ARBH),NaN,NaN
3,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Heart,0,0,,100,100,...,3.47,7.92,11.99,51,51,2012,7,Arkansas Children's Hospital (ARCH),NaN,NaN
4,UAMS Medical Center (ARUA),ARUA,TX1,2012/07/13,Heart,,,0,,,...,,,,,,2012,7,UAMS Medical Center (ARUA),NaN,NaN
5,Mayo Clinic Hospital (AZMC),AZMC,TX1,2012/07/13,Heart,1,2,8,97.56,94.77,...,,,,,,2012,7,Mayo Clinic Hospital (AZMC),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,University of Washington Medical Center (WAUW),WAUW,TX1,2014/06/17,Heart,7,7,5,85.71,85.71,...,,,0.16,,,2014,6,University of Washington Medical Center (WAUW),NaN,NaN
132,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Heart,0,1,3,100,87.5,...,1.32,3.39,5.16,36,36,2014,6,Children's Hospital of Wisconsin (WICH),NaN,NaN
133,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Heart,0,0,0,100,100,...,,,,,,2014,6,Froedtert Memorial Lutheran Hospital (WISE),NaN,NaN
134,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Heart,0,5,15,100,94.2,...,,,,,,2014,6,Aurora St. Luke's Medical Center (WISL),NaN,NaN
135,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Heart,0,2,5,100,94.02,...,,,,,,2014,6,University of Wisconsin Hospital and Clinics (...,NaN,NaN

In [7]:
column_adding['YEAR'].unique()

array(['2012', '2013', '2018', '2019', '2015', '2021', '2014', '2020',
       '2017', '2022', '2016'], dtype=object)

In [8]:
# df.loc[df['column_name'].isin(some_values)]

column_adding.loc[column_adding['YEAR']=='2012']

,Unnamed: 0,ctr_cd,ctr_ty,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_ACT_C1M,GSR_AD_ACT_C1Y,...,GSR_P0_EXP_C1M,GSR_P0_EXP_C1Y,GSR_P0_EXP_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH,ENTIRE_NAME,CTR_CD,CTR_TY
1,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Heart,0,2,12,100,94.51,...,0.32,0.80,1.69,13,13,2012,7,University of Alabama Hospital (ALUA),NaN,NaN
2,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Heart,0,2,10,100,89.95,...,,,,,,2012,7,Baptist Medical Center (ARBH),NaN,NaN
3,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Heart,0,0,,100,100,...,3.47,7.92,11.99,51,51,2012,7,Arkansas Children's Hospital (ARCH),NaN,NaN
4,UAMS Medical Center (ARUA),ARUA,TX1,2012/07/13,Heart,,,0,,,...,,,,,,2012,7,UAMS Medical Center (ARUA),NaN,NaN
5,Mayo Clinic Hospital (AZMC),AZMC,TX1,2012/07/13,Heart,1,2,8,97.56,94.77,...,,,,,,2012,7,Mayo Clinic Hospital (AZMC),NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135,University of Washington Medical Center (WAUW),WAUW,TX1,2012/07/13,Heart,2,3,3,96.77,95.16,...,0.02,0.06,0.11,1,1,2012,7,University of Washington Medical Center (WAUW),NaN,NaN
136,Children's Hospital of Wisconsin (WICH),WICH,TX1,2012/07/13,Heart,0,1,1,100,50,...,1.10,2.62,4.14,34,34,2012,7,Children's Hospital of Wisconsin (WICH),NaN,NaN
137,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2012/07/13,Heart,0,0,1,100,100,...,,,,,,2012,7,Froedtert Memorial Lutheran Hospital (WISE),NaN,NaN
138,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2012/07/13,Heart,7,13,6,91.14,82.33,...,,,,,,2012,7,Aurora St. Luke's Medical Center (WISL),NaN,NaN
139,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2012/07/13,Heart,0,3,8,100,94.12,...,,,,,,2012,7,University of Wisconsin Hospital and Clinics (...,NaN,NaN

In [9]:
column_adding.columns

Index(['Unnamed: 0', ' ctr_cd', 'ctr_ty', 'RELEASE_DATE', 'ORG',
       'GSR_AD_OBS_C1M', 'GSR_AD_OBS_C1Y', 'GSR_AD_OBS_C3Y', 'GSR_AD_ACT_C1M',
       'GSR_AD_ACT_C1Y', 'GSR_AD_ACT_C3Y', 'GSR_AD_ADJ_C1M', 'GSR_AD_ADJ_C1Y',
       'GSR_AD_ADJ_C3Y', 'GSR_AD_EXP_C1M', 'GSR_AD_EXP_C1Y', 'GSR_AD_EXP_C3Y',
       'GSR_AD_N_C1M', 'GSR_AD_N_C1Y', 'GSR_AD_N_C3Y', 'GSR_P0_OBS_C1M',
       'GSR_P0_OBS_C1Y', 'GSR_P0_OBS_C3Y', 'GSR_P0_ACT_C1M', 'GSR_P0_ACT_C1Y',
       'GSR_P0_ADJ_C1M', 'GSR_P0_ADJ_C1Y', 'GSR_P0_ADJ_C3Y', 'GSR_P0_EXP_C1M',
       'GSR_P0_EXP_C1Y', 'GSR_P0_EXP_C3Y', 'GSR_P0_N_C1M', 'GSR_P0_N_C1Y',
       'YEAR', 'MONTH', 'ENTIRE_NAME', 'CTR_CD', 'CTR_TY'],
      dtype='object')

In [10]:
# column_adding['ENTIRE_NAME'] = column_adding['ENTIRE_NAME'].fillna(column_adding['Unnamed: 0'])
column_adding['CTR_CD'] = column_adding['CTR_CD'].fillna(column_adding[' ctr_cd'])
column_adding['CTR_TY'] = column_adding['CTR_TY'].fillna(column_adding['ctr_ty'])

column_adding

,Unnamed: 0,ctr_cd,ctr_ty,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_ACT_C1M,GSR_AD_ACT_C1Y,...,GSR_P0_EXP_C1M,GSR_P0_EXP_C1Y,GSR_P0_EXP_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH,ENTIRE_NAME,CTR_CD,CTR_TY
1,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Heart,0,2,12,100,94.51,...,0.32,0.80,1.69,13,13,2012,7,University of Alabama Hospital (ALUA),ALUA,TX1
2,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Heart,0,2,10,100,89.95,...,,,,,,2012,7,Baptist Medical Center (ARBH),ARBH,TX1
3,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Heart,0,0,,100,100,...,3.47,7.92,11.99,51,51,2012,7,Arkansas Children's Hospital (ARCH),ARCH,TX1
4,UAMS Medical Center (ARUA),ARUA,TX1,2012/07/13,Heart,,,0,,,...,,,,,,2012,7,UAMS Medical Center (ARUA),ARUA,TX1
5,Mayo Clinic Hospital (AZMC),AZMC,TX1,2012/07/13,Heart,1,2,8,97.56,94.77,...,,,,,,2012,7,Mayo Clinic Hospital (AZMC),AZMC,TX1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,University of Washington Medical Center (WAUW),WAUW,TX1,2014/06/17,Heart,7,7,5,85.71,85.71,...,,,0.16,,,2014,6,University of Washington Medical Center (WAUW),WAUW,TX1
132,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Heart,0,1,3,100,87.5,...,1.32,3.39,5.16,36,36,2014,6,Children's Hospital of Wisconsin (WICH),WICH,TX1
133,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Heart,0,0,0,100,100,...,,,,,,2014,6,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1
134,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Heart,0,5,15,100,94.2,...,,,,,,2014,6,Aurora St. Luke's Medical Center (WISL),WISL,TX1
135,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Heart,0,2,5,100,94.02,...,,,,,,2014,6,University of Wisconsin Hospital and Clinics (...,WIUW,TX1

In [11]:
column_adding.loc[column_adding['YEAR']=='2021']

,Unnamed: 0,ctr_cd,ctr_ty,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_ACT_C1M,GSR_AD_ACT_C1Y,...,GSR_P0_EXP_C1M,GSR_P0_EXP_C1Y,GSR_P0_EXP_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH,ENTIRE_NAME,CTR_CD,CTR_TY
1,NaN,NaN,NaN,2021-07-06 19:00:00,HR,NaN,NaN,0,NaN,NaN,...,0.414586,1.358811,2.118928,19,19,2021,5,Children's of Alabama (ALCH),ALCH,TX1
2,NaN,NaN,NaN,2021-07-06 19:00:00,HR,1,2,1,97.959184,95.874946,...,NaN,NaN,NaN,NaN,NaN,2021,5,University of Alabama Hospital (ALUA),ALUA,TX1
3,NaN,NaN,NaN,2021-07-06 19:00:00,HR,2,4,6,91.666667,82.24537,...,NaN,NaN,NaN,NaN,NaN,2021,5,Baptist Medical Center (ARBH),ARBH,TX1
4,NaN,NaN,NaN,2021-07-06 19:00:00,HR,0,0,NaN,100,100,...,0.229268,0.630551,1.865878,11,11,2021,5,Arkansas Children's Hospital (ARCH),ARCH,TX1
5,NaN,NaN,NaN,2021-07-06 19:00:00,HR,NaN,NaN,NaN,NaN,NaN,...,0.655249,1.922749,5.233386,24,24,2021,5,Phoenix Children's Hospital (AZCH),AZCH,TX1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140,NaN,NaN,NaN,2022-01-06 18:00:00,HR,0,0,NaN,100,100,...,0.481257,1.424053,2.778306,18,18,2021,11,Children's Hospital of Wisconsin (WICH),WICH,TX1
141,NaN,NaN,NaN,2022-01-06 18:00:00,HR,0,2,6,100,93.841642,...,NaN,NaN,NaN,NaN,NaN,2021,11,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1
142,NaN,NaN,NaN,2022-01-06 18:00:00,HR,4,5,7,93.843145,92.003083,...,NaN,NaN,NaN,NaN,NaN,2021,11,Aurora St. Luke's Medical Center (WISL),WISL,TX1
143,NaN,NaN,NaN,2022-01-06 18:00:00,HR,5,8,6,93.055556,87.52267,...,NaN,NaN,NaN,NaN,NaN,2021,11,University of Wisconsin Hospital and Clinics (...,WIUW,TX1
144,NaN,NaN,NaN,2022-01-06 18:00:00,HR,0,0,NaN,100,100,...,NaN,NaN,NaN,NaN,NaN,2021,11,West Virginia University Hospital (WVWU),WVWU,TX1

In [12]:
survival_final = column_adding.drop(columns=['Unnamed: 0', ' ctr_cd', 'ctr_ty'])

survival_final

,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_ACT_C1M,GSR_AD_ACT_C1Y,GSR_AD_ACT_C3Y,GSR_AD_ADJ_C1M,GSR_AD_ADJ_C1Y,...,GSR_P0_EXP_C1M,GSR_P0_EXP_C1Y,GSR_P0_EXP_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH,ENTIRE_NAME,CTR_CD,CTR_TY
1,2012/07/13,Heart,0,2,12,100,94.51,70.73,97.02,92.68,...,0.32,0.80,1.69,13,13,2012,7,University of Alabama Hospital (ALUA),ALUA,TX1
2,2012/07/13,Heart,0,2,10,100,89.95,68.75,96.49,91.49,...,,,,,,2012,7,Baptist Medical Center (ARBH),ARBH,TX1
3,2012/07/13,Heart,0,0,,100,100,,93.40,84.21,...,3.47,7.92,11.99,51,51,2012,7,Arkansas Children's Hospital (ARCH),ARCH,TX1
4,2012/07/13,Heart,,,0,,,100.00,,,...,,,,,,2012,7,UAMS Medical Center (ARUA),ARUA,TX1
5,2012/07/13,Heart,1,2,8,97.56,94.77,82.22,96.26,90.92,...,,,,,,2012,7,Mayo Clinic Hospital (AZMC),AZMC,TX1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,2014/06/17,Heart,7,7,5,85.71,85.71,91.94,96.60,91.80,...,,,0.16,,,2014,6,University of Washington Medical Center (WAUW),WAUW,TX1
132,2014/06/17,Heart,0,1,3,100,87.5,0.00,96.75,92.17,...,1.32,3.39,5.16,36,36,2014,6,Children's Hospital of Wisconsin (WICH),WICH,TX1
133,2014/06/17,Heart,0,0,0,100,100,100.00,97.65,94.28,...,,,,,,2014,6,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1
134,2014/06/17,Heart,0,5,15,100,94.2,73.68,95.85,90.11,...,,,,,,2014,6,Aurora St. Luke's Medical Center (WISL),WISL,TX1
135,2014/06/17,Heart,0,2,5,100,94.02,89.36,96.47,91.51,...,,,,,,2014,6,University of Wisconsin Hospital and Clinics (...,WIUW,TX1

In [13]:
first_column = survival_final.pop('ENTIRE_NAME')
second_column = survival_final.pop('CTR_CD')
third_column = survival_final.pop('CTR_TY')

survival_final.insert(0, 'ENTIRE_NAME', first_column)
survival_final.insert(1, 'CTR_CD', second_column)
survival_final.insert(2, 'CTR_TY', third_column)

survival_final

,ENTIRE_NAME,CTR_CD,CTR_TY,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_ACT_C1M,GSR_AD_ACT_C1Y,...,GSR_P0_ADJ_C1M,GSR_P0_ADJ_C1Y,GSR_P0_ADJ_C3Y,GSR_P0_EXP_C1M,GSR_P0_EXP_C1Y,GSR_P0_EXP_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH
1,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Heart,0,2,12,100,94.51,...,97.59,93.69,85.83,0.32,0.80,1.69,13,13,2012,7
2,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Heart,0,2,10,100,89.95,...,,,,,,,,,2012,7
3,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Heart,0,0,,100,100,...,93.70,84.85,75.14,3.47,7.92,11.99,51,51,2012,7
4,UAMS Medical Center (ARUA),ARUA,TX1,2012/07/13,Heart,,,0,,,...,,,,,,,,,2012,7
5,Mayo Clinic Hospital (AZMC),AZMC,TX1,2012/07/13,Heart,1,2,8,97.56,94.77,...,,,,,,,,,2012,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,University of Washington Medical Center (WAUW),WAUW,TX1,2014/06/17,Heart,7,7,5,85.71,85.71,...,,,85.32,,,0.16,,,2014,6
132,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Heart,0,1,3,100,87.5,...,96.46,89.22,83.06,1.32,3.39,5.16,36,36,2014,6
133,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Heart,0,0,0,100,100,...,,,,,,,,,2014,6
134,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Heart,0,5,15,100,94.2,...,,,,,,,,,2014,6
135,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Heart,0,2,5,100,94.02,...,,,,,,,,,2014,6

In [14]:
survival_final = survival_final.replace(r'^\s*$', np.nan, regex=True)

survival_final

,ENTIRE_NAME,CTR_CD,CTR_TY,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_ACT_C1M,GSR_AD_ACT_C1Y,...,GSR_P0_ADJ_C1M,GSR_P0_ADJ_C1Y,GSR_P0_ADJ_C3Y,GSR_P0_EXP_C1M,GSR_P0_EXP_C1Y,GSR_P0_EXP_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH
1,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Heart,0,2,12,100,94.51,...,97.59,93.69,85.83,0.32,0.80,1.69,13,13,2012,7
2,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Heart,0,2,10,100,89.95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,7
3,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Heart,0,0,NaN,100,100,...,93.70,84.85,75.14,3.47,7.92,11.99,51,51,2012,7
4,UAMS Medical Center (ARUA),ARUA,TX1,2012/07/13,Heart,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,7
5,Mayo Clinic Hospital (AZMC),AZMC,TX1,2012/07/13,Heart,1,2,8,97.56,94.77,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,University of Washington Medical Center (WAUW),WAUW,TX1,2014/06/17,Heart,7,7,5,85.71,85.71,...,NaN,NaN,85.32,NaN,NaN,0.16,NaN,NaN,2014,6
132,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Heart,0,1,3,100,87.5,...,96.46,89.22,83.06,1.32,3.39,5.16,36,36,2014,6
133,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Heart,0,0,0,100,100,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014,6
134,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Heart,0,5,15,100,94.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014,6
135,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Heart,0,2,5,100,94.02,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2014,6

In [15]:
survival_final = survival_final.fillna(0)

survival_final

,ENTIRE_NAME,CTR_CD,CTR_TY,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_ACT_C1M,GSR_AD_ACT_C1Y,...,GSR_P0_ADJ_C1M,GSR_P0_ADJ_C1Y,GSR_P0_ADJ_C3Y,GSR_P0_EXP_C1M,GSR_P0_EXP_C1Y,GSR_P0_EXP_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH
1,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Heart,0,2,12,100,94.51,...,97.59,93.69,85.83,0.32,0.80,1.69,13,13,2012,7
2,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Heart,0,2,10,100,89.95,...,0,0,0,0,0,0,0,0,2012,7
3,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Heart,0,0,0,100,100,...,93.70,84.85,75.14,3.47,7.92,11.99,51,51,2012,7
4,UAMS Medical Center (ARUA),ARUA,TX1,2012/07/13,Heart,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2012,7
5,Mayo Clinic Hospital (AZMC),AZMC,TX1,2012/07/13,Heart,1,2,8,97.56,94.77,...,0,0,0,0,0,0,0,0,2012,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,University of Washington Medical Center (WAUW),WAUW,TX1,2014/06/17,Heart,7,7,5,85.71,85.71,...,0,0,85.32,0,0,0.16,0,0,2014,6
132,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Heart,0,1,3,100,87.5,...,96.46,89.22,83.06,1.32,3.39,5.16,36,36,2014,6
133,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Heart,0,0,0,100,100,...,0,0,0,0,0,0,0,0,2014,6
134,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Heart,0,5,15,100,94.2,...,0,0,0,0,0,0,0,0,2014,6
135,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Heart,0,2,5,100,94.02,...,0,0,0,0,0,0,0,0,2014,6

In [16]:
final_df = survival_final.copy()
final_df

,ENTIRE_NAME,CTR_CD,CTR_TY,RELEASE_DATE,ORG,GSR_AD_OBS_C1M,GSR_AD_OBS_C1Y,GSR_AD_OBS_C3Y,GSR_AD_ACT_C1M,GSR_AD_ACT_C1Y,...,GSR_P0_ADJ_C1M,GSR_P0_ADJ_C1Y,GSR_P0_ADJ_C3Y,GSR_P0_EXP_C1M,GSR_P0_EXP_C1Y,GSR_P0_EXP_C3Y,GSR_P0_N_C1M,GSR_P0_N_C1Y,YEAR,MONTH
1,University of Alabama Hospital (ALUA),ALUA,TX1,2012/07/13,Heart,0,2,12,100,94.51,...,97.59,93.69,85.83,0.32,0.80,1.69,13,13,2012,7
2,Baptist Medical Center (ARBH),ARBH,TX1,2012/07/13,Heart,0,2,10,100,89.95,...,0,0,0,0,0,0,0,0,2012,7
3,Arkansas Children's Hospital (ARCH),ARCH,TX1,2012/07/13,Heart,0,0,0,100,100,...,93.70,84.85,75.14,3.47,7.92,11.99,51,51,2012,7
4,UAMS Medical Center (ARUA),ARUA,TX1,2012/07/13,Heart,0,0,0,0,0,...,0,0,0,0,0,0,0,0,2012,7
5,Mayo Clinic Hospital (AZMC),AZMC,TX1,2012/07/13,Heart,1,2,8,97.56,94.77,...,0,0,0,0,0,0,0,0,2012,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131,University of Washington Medical Center (WAUW),WAUW,TX1,2014/06/17,Heart,7,7,5,85.71,85.71,...,0,0,85.32,0,0,0.16,0,0,2014,6
132,Children's Hospital of Wisconsin (WICH),WICH,TX1,2014/06/17,Heart,0,1,3,100,87.5,...,96.46,89.22,83.06,1.32,3.39,5.16,36,36,2014,6
133,Froedtert Memorial Lutheran Hospital (WISE),WISE,TX1,2014/06/17,Heart,0,0,0,100,100,...,0,0,0,0,0,0,0,0,2014,6
134,Aurora St. Luke's Medical Center (WISL),WISL,TX1,2014/06/17,Heart,0,5,15,100,94.2,...,0,0,0,0,0,0,0,0,2014,6
135,University of Wisconsin Hospital and Clinics (...,WIUW,TX1,2014/06/17,Heart,0,2,5,100,94.02,...,0,0,0,0,0,0,0,0,2014,6

In [17]:
final_df.to_csv("Resources/HR_survival.csv", index=False, header=True)